version: '3.8'

services:
  cli-app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: bee-cli-app
    container_name: bee-cli-container
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    user: appuser
    environment:
      - DEVCONTAINER=true
    stdin_open: true
    privileged: true