version: '3.8'

services:
  app:
    image: node:18
    container_name: my_app
    working_dir: /workspace
    volumes:
      - .:/workspace
    ports:
      - "3000:3000"
    command: "npm start"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: my_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
